services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paypilot
    ports:
      - "5433:5432"
    networks:
      - app_network

  app:
    image: mypilot
    container_name: springboot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paypilot
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
    depends_on:
      - postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
